language: php

php:
  - 5.5
  - 5.6
  - hhvm

allow_failures:
  - php: hhvm

services: mysql

before_script:
  - mysql < logos_unit.sql
  - composer self-update
  # --prefer-source is required to avoid hitting GitHub API limit:
  # https://github.com/composer/composer/issues/1314
  - composer install --no-interaction --prefer-source


script:
  - phpunit --verbose